--- # ItemLifeTime plugin configuration file

# Set dropped item lifetime in your server (in second)
# Default is 300 seconds (5 minutes)
# Minimum value is 0, maximum is 1938
# Item will never despawn if this set to -1
item-lifetime: 300

# Set different custom item lifetime on each of these worlds (optional)
# Value in item-lifetime will be used if the world is not set in this list
# Example configuration:
# worlds:
#   MyPrettyWorld: 120
#   MyDirtyWorld: 360
#
# This will set item lifetime in MyPrettyWorld world to 120 seconds, 360 seconds in MyDirtyWorld
worlds: {}

# Show remaining time to disappear in item's nametag
display-time:
  # Set this to false if your server is lagging
  enabled: false
  # Text to be set in item's nametag
  # {MINUTE}, {SECOND}, {TIME}
  # Set this to "{MINUTE}:{SECOND} {TIME}" will be shown as "01:20 01 minute" (example)
  text: "{MINUTE}:{SECOND}"
...
