--- # ItemLifeTime plugin configuration file

# Set dropped item lifetime in your server (in second)
# Default is 5 minutes (300 seconds)
# Minimum value is 0, maximum is 1938
# Item will never despawn if this set to -1
item-lifetime: 300

# Set different custom item lifetime on each of these worlds (optional)
# Example configuration:
# worlds:
#   MyPrettyWorld: 120
#   MyBadWorld: 360
#
# This will set item lifetime in MyPrettyWorld world to 120 seconds, 360 seconds in MyBadWorld, else 300
# seconds in the other worlds
worlds: {}
...
